In [1]:
from bs4 import BeautifulSoup
import requests
import time
import pandas as pd

In [41]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

In [42]:
all_disasters = []

In [25]:
url = 'https://reliefweb.int/disasters?page=0'

In [26]:
page = requests.get(url, headers=headers)

In [27]:
soup = BeautifulSoup(page.text, 'html')

In [28]:
print(soup.prettify())

<!DOCTYPE html>
<html class="no-js" dir="ltr" lang="en" prefix="og: https://ogp.me/ns#">
 <head>
  <meta charset="utf-8"/>
  <script>
   document.documentElement.className = document.documentElement.className.replace('no-js', typeof document.addEventListener !== 'undefined' ? 'js' : 'no-js');
  </script>
  <meta content="ReliefWeb disaster pages provide an overview of the situation and situation reports, news and press releases, assessments, evaluations, infographics and maps. Browse our list of natural disasters with humanitarian impact from 1981 until today." name="description"/>
  <link href="https://reliefweb.int/disasters" rel="canonical"/>
  <link href="https://reliefweb.int/modules/custom/reliefweb_meta/images/default.png" rel="image_src"/>
  <meta content="ReliefWeb" property="og:site_name"/>
  <meta content="article" property="og:type"/>
  <meta content="https://reliefweb.int/disasters" property="og:url"/>
  <meta content="Disasters" property="og:title"/>
  <meta content="ReliefWeb disaster pages provide an overview of the situation and situation reports, news and press releases, assessments, evaluations, infographics and maps. Browse our list of natural disasters with humanitarian impact from 1981 until today." property="og:description"/>
  <meta content="https://reliefweb.int/modules/custom/reliefweb_meta/images/default.png" property="og:image"/>
  <meta content="1916193535375038" property="fb:app_id"/>
  <meta content="summary" name="twitter:card"/>
  <meta content="@reliefweb" name="twitter:site"/>
  <meta content="width" name="MobileOptimized"/>
  <meta content="true" name="HandheldFriendly"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link href="/themes/custom/common_design_subtheme/favicon.ico" rel="icon" type="image/vnd.microsoft.icon"/>
  <link href="https://fonts.googleapis.com" rel="preconnect"/>
  <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
  <link as="style" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,400;1,700&amp;display=swap" onload="this.onload=null;this.setAttribute(`rel`, `stylesheet`);" rel="preload"/>
  <link as="image" href="https://reliefweb.int/themes/custom/common_design_subtheme/img/logos/rw-logo-desktop.svg" rel="preload"/>
  <link as="image" href="https://reliefweb.int/themes/custom/common_design_subtheme/img/logos/rw-logo-mobile.svg" media="(max-width: 768px)" rel="preload"/>
  <link as="image" href="https://reliefweb.int/themes/custom/common_design_subtheme/img/logos/ocha-logo-sprite.svg" rel="preload"/>
  <link as="image" href="https://reliefweb.int/themes/custom/common_design_subtheme/components/rw-icons/img/rw-icons-sprite.svg?v=1.0.4" rel="preload"/>
  <link as="image" href="https://reliefweb.int/themes/custom/common_design_subtheme/img/logos/rw-logo-sprite.svg" rel="preload"/>
  <script type="text/javascript">
   dataLayer = [{"dimension12":"anonymous user"}];
  </script>
  <title>
   Disasters | ReliefWeb
  </title>
  <link href="/sites/default/files/css/css_ujF844rsTxJz56RjA94K6hoql77vtZ65otQfz-QzZ1g.css?delta=0&amp;language=en&amp;theme=common_design_subtheme&amp;include=eJyNkEGuwjAMBS_UqEeqnMQUCydGtttSTk9Y_AU_UmARyXozm0mSUqQuGY3WOqccIku6BSdnnFIHN3ep_X5hOfq1Srv7eXNicurQyhKBg_nJVNdPuNgW_YoFf7T0CJB3qAlzMARN15GpTul_7oeRycAcNRS4_6DZwMHa_vYMBR0G1h1W1AFX2of8a_NOeIQi-q5WnKtoAaYnTopMeDkwLn81S4ue24vymOxsS5kjGL4A6kTf7g" media="all" rel="stylesheet"/>
  <link href="/mapbox/mapbox-gl-js/v1.7.0/mapbox-gl.css" media="all" rel="stylesheet"/>
  <link href="/sites/default/files/css/css_qoMb_loK7MURGc9xgsiytxyTt9iUsnr9LGaYyrfYnck.css?delta=2&amp;language=en&amp;theme=common_design_subtheme&amp;include=eJyNkEGuwjAMBS_UqEeqnMQUCydGtttSTk9Y_AU_UmARyXozm0mSUqQuGY3WOqccIku6BSdnnFIHN3ep_X5hOfq1Srv7eXNicurQyhKBg_nJVNdPuNgW_YoFf7T0CJB3qAlzMARN15GpTul_7oeRycAcNRS4_6DZwMHa_vYMBR0G1h1W1AFX2of8a_NOeIQi-q5WnKtoAaYnTopMeDkwLn81S4ue24vymOxsS5kjGL4A6kTf7g" media="all" rel="stylesheet"/>
 </head>
 <body class="path-disasters">
  <a class="visually-hidden focusable skip-link" href="#main-content">
   Skip to main content
  </a>
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-TLKXSWT&gt;m_auth=&gt;m_preview=&gt;m_cookies_win=x" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-LQCS&gt;m_auth=&gt;m_preview=&gt;m_cookies_win=x" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <div class="dialog-off-canvas-main-canvas" data-off-canvas-main-canvas="">
   <div class="cd-page-layout-container">
    <header aria-label="Site header" class="cd-header">
     <div class="cd-global-header">
      <div class="cd-container cd-global-header__inner">
       <div class="region region-header-top cd-global-header__actions" id="cd-global-header__actions">
        <nav aria-label="Help" class="block block-menu navigation menu--help cd-global-header__user-menu cd-user-menu" id="block-help">
         <ul class="menu">
          <li class="menu-item">
           <a href="/help" id="cd-help-menu-0-item-1">
            <svg aria-hidden="true" class="cd-icon cd-icon--help" focusable="false" height="16" width="16">
             <use xlink:href="#cd-icon--help">
             </use>
            </svg>
            <span>
             Help
            </span>
           </a>
          </li>
         </ul>
        </nav>
        <nav aria-label="Account" class="block block-menu navigation menu--account cd-global-header__user-menu cd-user-menu" id="block-useraccountmenu">
         <a href="/user/login" id="cd-user-menu-0-item-1">
          <svg aria-hidden="true" class="cd-icon cd-icon--user" focusable="false" height="16" width="16">
           <use xlink:href="#cd-icon--user">
           </use>
          </svg>
          <span>
           Log in
          </span>
         </a>
        </nav>
       </div>
      </div>
     </div>
     <div class="cd-site-header">
      <div class="cd-container cd-site-header__inner">
       <div class="region region-header-logo">
        <a class="cd-site-logo" href="/" rel="home" title="Front page">
         <img alt="ReliefWeb logo" aria-hidden="true" height="40" src="/themes/custom/common_design_subtheme/img/logos/rw-logo-desktop.svg" width="160"/>
         <span class="visually-hidden">
          ReliefWeb
         </span>
        </a>
       </div>
       <div class="cd-site-header__actions">
        <div class="cd-search">
         <section aria-labelledby="site-search-title" class="cd-search__form" data-cd-component="cd-search" data-cd-focus-target="site-search-input" data-cd-logo="search" data-cd-toggable="Search" id="site-search" role="search">
          <h2 class="visually-hidden" id="site-search-title">
           Content Search
          </h2>
          <form accept-charset="UTF-8" action="/search/results" class="[ cd-flow ]" method="GET">
           <div class="form--inline clearfix">
            <div class="cd-form__item form-type-textfield">
             <label class="visually-hidden" for="site-search-input">
              What are you looking for?
             </label>
             <input autocomplete="off" class="cd-search__input" id="site-search-input" name="search" placeholder="What are you looking for?" size="30" type="text"/>
            </div>
            <div class="cd-form__item form-actions">
             <button class="cd-search__submit" type="submit" value="search">
              <svg class="cd-icon cd-icon--search" height="16" width="16">
               <use xlink:href="#cd-icon--search">
               </use>
              </svg>
              <span class="visually-hidden">
               Search|t
              </span>
             </button>
            </div>
           </div>
          </form>
         </section>
        </div>
        <div class="cd-site-header__nav-holder">
         <nav aria-label="Main" class="block block-menu navigation menu--main cd-nav cd-site-header__nav" data-cd-component="cd-nav-level-0" data-cd-icon="arrow-down" data-cd-toggable="Menu" id="block-mainnavigation">
          <ul class="menu cd-nav__menu--level-1" role="list">
           <li class="menu-item cd-nav__menu-item--level-1">
            <a class="cd-nav__btn cd-nav-level-1__btn" href="/updates" id="cd-nav-level-10-item-1">
             <span>
              Updates
             </span>
            </a>
           </li>
           <li class="menu-item cd-nav__menu-item--level-1">
            <a class="cd-nav__btn cd-nav-level-1__btn" href="/countries" id="cd-nav-level-10-item-2">
             <span>
              Countries
             </span>
            </a>
           </li>
           <li class="menu-item cd-nav__menu-item--level-1 menu-item--active-trail">
            <a class="cd-nav__btn cd-nav-level-1__btn" href="/disasters" id="cd-nav-level-10-item-3">
             <span>
              Disasters
             </span>
            </a>
           </li>
           <li class="menu-item cd-nav__menu-item--level-1">
            <a class="cd-nav__btn cd-nav-level-1__btn" href="/organizations" id="cd-nav-level-10-item-4">
             <span>
              Organizations
             </span>
            </a>
           </li>
           <li class="menu-item cd-nav__menu-item--level-1">
            <a class="cd-nav__btn cd-nav-level-1__btn" href="/topics" id="cd-nav-level-10-item-5">
             <span>
              Topics
             </span>
            </a>
           </li>
           <li class="menu-item cd-nav__menu-item--level-1">
            <a class="cd-nav__btn cd-nav-level-1__btn" href="/jobs" id="cd-nav-level-10-item-6">
             <span>
              Jobs
             </span>
            </a>
           </li>
           <li class="menu-item cd-nav__menu-item--level-1">
            <a class="cd-nav__btn cd-nav-level-1__btn" href="/training" id="cd-nav-level-10-item-7">
             <span>
              Training
             </span>
            </a>
           </li>
          </ul>
         </nav>
        </div>
       </div>
      </div>
     </div>
     <div id="site-slogan">
      <div class="cd-container">
       <span>
        Informing humanitarians worldwide 24/7 —
        <span>
         a service provided by
         <span class="ocha">
          UN OCHA
         </span>
        </span>
       </span>
      </div>
     </div>
    </header>
    <div class="cd-layout-highlighted cd-container">
     <div class="region region-highlighted">
      <div class="hidden" data-drupal-messages-fallback="">
      </div>
     </div>
    </div>
    <main aria-label="Page content" class="cd-container" id="main-content">
     <div class="cd-layout">
      <div class="cd-layout__content">
       <div class="region region-content">
        <section class="rw-river-page rw-river-page--disasters rw-river-page--disasters--all rw-river-page--with-views rw-river-page--with-pre-content rw-river-page--with-search rw-river-page--with-advanced-search rw-river-page--with-links">
         <header class="rw-river-page__header">
          <h1 class="rw-page-title rw-river-page__title visually-hidden">
           Disasters
          </h1>
          <nav class="rw-river-views" id="river-views">
           <h2 class="rw-river-views__title visually-hidden">
            Views
           </h2>
           <ul id="rw-river-views__list">
            <li class="rw-river-views__list__item rw-river-views__list__item--selected">
             <a class="rw-river-views__link" data-default="" data-view="all" href="/disasters">
              All Disasters
             </a>
            </li>
            <li class="rw-river-views__list__item">
             <a class="rw-river-views__link" data-view="ongoing" href="/disasters?list=Alert%20/%20Ongoing&amp;view=ongoing">
              Alert / Ongoing
             </a>
            </li>
           </ul>
          </nav>
         </header>
         <section class="rw-disaster-map [ cd-flow ] rw-river rw-river--disaster-map" data-disaster-map="disaster-map" data-map-enabled="" id="disaster-map">
          <h2 class="rw-disaster-map__title cd-block-title rw-river__title">
           Alert and Ongoing Disasters
          </h2>
          <div class="rw-disaster-map__content [ cd-flow ] rw-river__articles" data-map-content="">
           <article class="rw-disaster-map__article rw-river-article rw-river-article--disaster" data-disaster-lat="-2.28" data-disaster-lon="117.37" data-disaster-status="ongoing" data-disaster-type="EQ" data-id="52676">
            <header class="rw-river-article__header">
             <h3 class="rw-river-article__title" lang="en">
              <a href="https://reliefweb.int/disaster/eq-2026-000150-idn">
               Indonesia: Earthquake - Aug 2026
              </a>
             </h3>
            </header>
            <div class="rw-river-article__content" lang="en">
             <p>
              A magnitude 7.7 earthquake struck offshore Nagekeo Regency, East Nusa Tenggara Province, on 15 August 2026 at 04:58 WIB. The earthquake occurred at a depth of 15 km, approximately 38 km northeast of Mbay. The tsunami warning issued for several coastal areas...
             </p>
            </div>
            <footer class="rw-river-article__footer">
             <dl class="rw-meta rw-article-meta rw-entity-meta rw-entity-meta--core">
              <dt class="rw-entity-meta__tag-label rw-entity-meta__tag-label--status">
               Status
              </dt>
              <dd class="rw-entity-meta__tag-value--status--ongoing rw-entity-meta__tag-value rw-entity-meta__tag-value--status rw-entity-meta__tag-value--simple">
               Ongoing
              </dd>
              <dt class="rw-entity-meta__tag-label rw-entity-meta__tag-label--disaster-type">
               Disaster type
              </dt>
              <dd class="rw-entity-meta__tag-value rw-entity-meta__tag-value--disaster-type rw-entity-meta__tag-value--taglist">
               <ul class="rw-entity-meta__tag-value__list">
                <li class="rw-entity-meta__tag-value__list__item rw-entity-meta__tag-value__list__item--last">
                 <a class="rw-entity-meta__tag-link" href="/disasters?list=Earthquake%20Disasters&amp;advanced-search=%28TY4628%29">
                  Earthquake
                 </a>
                </li>
               </ul>
              </dd>
              <dt class="rw-entity-meta__tag-label rw-entity-meta__tag-label--country">
               Affected country
              </dt>
              <dd class="rw-entity-meta__tag-value rw-entity-meta__tag-value--country rw-entity-meta__tag-value--taglist rw-entity-meta__tag-value--last">
               <ul class="rw-entity-meta__tag-value__list">
                <li class="rw-entity-meta__tag-value__list__item rw-entity-meta__tag-value__list__item--last">
                 <a class="rw-entity-meta__tag-link" href="/country/idn">
                  Indonesia
                 </a>
                </li>
               </ul>
              </dd>
             </dl>
            </footer>
           </article>
           <article class="rw-disaster-map__article rw-river-article rw-river-article--disaster" data-disaster-lat="3.9" data-disaster-lon="-73.07" data-disaster-status="ongoing" data-disaster-type="EQ" data-id="52670">
            <header class="rw-river-article__header">
             <h3 class="rw-river-article__title" lang="en">
              <a href="https://reliefweb.int/disaster/eq-2026-000146-col">
               Colombia: Earthquake - Aug 2026
              </a>
             </h3>
            </header>
            <div class="rw-river-article__content" lang="en">
             <p>
              According to information from the Colombian Geological Service (SGC), an earthquake with a preliminary magnitude of 7.4 was recorded on Monday, August 10, 2026, in the morning, with its epicenter in the town of San José del Palmar, in the department of Chocó,...
             </p>
            </div>
            <footer class="rw-river-article__footer">
             <dl class="rw-meta rw-article-meta rw-entity-meta rw-entity-meta--core">
              <dt class="rw-entity-meta__tag-label rw-entity-meta__tag-label--status">
               Status
              </dt>
              <dd class="rw-entity-meta__tag-value--status--ongoing rw-entity-meta__tag-value rw-entity-meta__tag-value--status rw-entity-meta__tag-value--simple">
               Ongoing
              </dd>
              <dt class="rw-entity-meta__tag-label rw-entity-meta__tag-label--disaster-type">
               Disaster type
              </dt>
              <dd class="rw-entity-meta__tag-value rw-entity-meta__tag-value--disaster-type rw-entity-meta__tag-value--taglist">
               <ul class="rw-entity-meta__tag-value__list">
                <li class="rw-entity-meta__tag-value__list__item rw-entity-meta__tag-value__list__item--last">
                 <a class="rw-entity-meta__tag-link" href="/disasters?list=Earthquake%20Disasters&amp;advanced-search=%28TY4628%29">
                  Earthquake
                 </a>
                </li>
               </ul>
              </dd>
              <dt class="rw-entity-meta__tag-label rw-entity-meta__tag-label--country">
               Affected country
              </dt>
              <dd class="rw-entity-meta__tag-value rw-entity-meta__tag-value--country rw-entity-meta__tag-value--taglist rw-entity-meta__tag-value--last">
               <ul class="rw-entity-meta__tag-value__list">
                <li class="rw-entity-meta__tag-value__list__item rw-entity-meta__tag-value__list__item--last">
                 <a class="rw-entity-meta__tag-link" href="/country/col">
                  Colombia
                 </a>
                </li>
               </ul>
              </dd>
             </dl>
             <section class="rw-river-article--disaster__related-disasters">
              <h4 class="rw-river-article--disaster__related-disasters__title">
               Related disasters
              </h4>
              <ul aria-label="Disasters related to Colombia: Earthquake - Aug 2026" class="rw-river-article--disaster__related-disasters__list">
               <li class="rw-river-article--disaster__related-disasters__list__item" data-disaster-status="ongoing" data-disaster-type="FL">
                <a href="https://reliefweb.int/disaster/fl-2026-000017-col">
                 Colombia: Floods - Jan 2026
                </a>
               </li>
              </ul>
             </section>
            </footer>
           </article>
           <article class="rw-disaster-map__article rw-river-article rw-river-article--disaster" data-disaster-lat="21.15" data-disaster-lon="96.51" data-disaster-status="ongoing" data-disaster-type="FL" data-id="52658">
            <header class="rw-river-article__header">
             <h3 class="rw-river-article__title" lang="en">
              <a href="https://reliefweb.int/disaster/fl-2026-000141-mmr">
               Myanmar: Floods - Jul 2026
              </a>
             </h3>
            </header>
            <div class="rw-river-article__content" lang="en">
             <p>
              Heavy and continuous monsoon rainfall caused rising water levels and flooding across low-lying and flood-prone areas of Ayeyarwady Region. The situation escalated on 30 July 2026, when an embankment near Myit Kyo Village in Laymyatna Township breached, and...
             </p>
            </div>
            <footer class="rw-river-article__footer">
             <dl class="rw-meta rw-article-meta rw-entity-meta rw-entity-meta--core">
              <dt class="rw-entity-meta__tag-label rw-entity-meta__tag-label--status">
               Status
              </dt>

In [29]:
soup.find('table', class_ = 'table')

In [32]:
table = soup.find_all('dt')[1]

In [33]:
table

In [43]:
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
all_disasters = [] 

# Scraping the first 3 pages as a test
for page_num in range(1, 150):
    url = f"https://reliefweb.int/disasters?page={page_num}"
    print(f"Scraping page {page_num}...")
    
    response = requests.get(url, headers=headers)
    
    if response.status_code == 200:
        print(f'{page_num} is working')
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # 1. titles are stored inside <h3> tags
        # We locate all h3 tags on the page
        title_tags = soup.find_all('h3') 
        
        for tag in title_tags:
            # Get the raw text of the title (e.g., "Colombia: Earthquake - Aug 2024")
            raw_title = tag.text.strip()
            
            # Skip any h3 tags that aren't actually disaster titles 
            if ":" not in raw_title or "-" not in raw_title:
                continue 
                
            try:
                # 2.we Split the string into usable data!
                # First, split by ":" to separate the Country from the rest of the data's
                country = raw_title.split(':')[0].strip()
                
                # Next, we take the second section and split by "-" to separate Disaster from Date
                remainder = raw_title.split(':')[1]
                disaster_type = remainder.split('-')[0].strip()
                date = remainder.split('-')[1].strip()
                
                # 3. Add these data's to our all_disasters list
                all_disasters.append([country, disaster_type, date, raw_title])
                
            except IndexError:
                # If a title is formatted incorrectly, we continue 
                continue
                
    time.sleep(2) 

print("Scraping complete!")

Scraping page 1...
Scraping page 2...
Scraping page 3...
Scraping page 4...
Scraping page 5...
Scraping page 6...
Scraping page 7...
Scraping page 8...
Scraping page 9...
Scraping page 10...
Scraping page 11...
Scraping page 12...
Scraping page 13...
Scraping page 14...
Scraping page 15...
Scraping page 16...
Scraping page 17...
Scraping page 18...
Scraping page 19...
Scraping page 20...
Scraping page 21...
Scraping page 22...
Scraping page 23...
Scraping page 24...
Scraping page 25...
Scraping page 26...
Scraping page 27...
Scraping page 28...
Scraping page 29...
Scraping page 30...
Scraping page 31...
Scraping page 32...
Scraping page 33...
Scraping page 34...
Scraping page 35...
Scraping page 36...
Scraping page 37...
Scraping page 38...
Scraping page 39...
Scraping page 40...
Scraping page 41...
Scraping page 42...
Scraping page 43...
Scraping page 44...
Scraping page 45...
Scraping page 46...
Scraping page 47...
Scraping page 48...
Scraping page 49...
Scraping page 50...
Scraping page 51...
Scraping page 52...
Scraping page 53...
Scraping page 54...
Scraping page 55...
Scraping page 56...
Scraping page 57...
Scraping page 58...
Scraping page 59...
Scraping page 60...
Scraping page 61...
Scraping page 62...
Scraping page 63...
Scraping page 64...
Scraping page 65...
Scraping page 66...
Scraping page 67...
Scraping page 68...
Scraping page 69...
Scraping page 70...
Scraping page 71...
Scraping page 72...
Scraping page 73...
Scraping page 74...
Scraping page 75...
Scraping page 76...
Scraping page 77...
Scraping page 78...
Scraping page 79...
Scraping page 80...
Scraping page 81...
Scraping page 82...
Scraping page 83...
Scraping page 84...
Scraping page 85...
Scraping page 86...
Scraping page 87...
Scraping page 88...
Scraping page 89...
Scraping page 90...
Scraping page 91...
Scraping page 92...
Scraping page 93...
Scraping page 94...
Scraping page 95...
Scraping page 96...
Scraping page 97...
Scraping page 98...
Scraping page 99...
Scraping page 100...
Scraping page 101...
Scraping page 102...
Scraping page 103...
Scraping page 104...
Scraping page 105...
Scraping page 106...
Scraping page 107...
Scraping page 108...
Scraping page 109...
Scraping page 110...
Scraping page 111...
Scraping page 112...
Scraping page 113...
Scraping page 114...
Scraping page 115...
Scraping page 116...
Scraping page 117...
Scraping page 118...
Scraping page 119...
Scraping page 120...
Scraping page 121...
Scraping page 122...
Scraping page 123...
Scraping page 124...
Scraping page 125...
Scraping page 126...
Scraping page 127...
Scraping page 128...
Scraping page 129...
Scraping page 130...
Scraping page 131...
Scraping page 132...
Scraping page 133...
Scraping page 134...
Scraping page 135...
Scraping page 136...
Scraping page 137...
Scraping page 138...
Scraping page 139...
Scraping page 140...
Scraping page 141...
Scraping page 142...
Scraping page 143...
Scraping page 144...
Scraping page 145...
Scraping page 146...
Scraping page 147...
Scraping page 148...
Scraping page 149...
Scraping complete!

In [46]:
df = pd.DataFrame(all_disasters, columns=['Country', 'Disaster_Type', 'Date', 'Original_Title'])

df.head(10)

,Country,Disaster_Type,Date,Original_Title
0,Indonesia,Earthquake,Aug 2026,Indonesia: Earthquake - Aug 2026
1,Colombia,Earthquake,Aug 2026,Colombia: Earthquake - Aug 2026
2,Myanmar,Floods,Jul 2026,Myanmar: Floods - Jul 2026
3,Afghanistan,Flash Floods,Jul 2026,Afghanistan: Flash Floods - Jul 2026
4,India,Flash Floods,Jul 2026,India: Flash Floods - Jul 2026
5,Kyrgyzstan,Flash Floods,Jul 2026,Kyrgyzstan: Flash Floods - Jul 2026
6,Tajikistan,Floods,Jul 2026,Tajikistan: Floods - Jul 2026
7,Bangladesh,Flash Floods,Jul 2026,Bangladesh: Flash Floods - Jul 2026
8,Georgia,Floods,Jun 2026,Georgia: Floods - Jun 2026
9,Central African Republic,Cholera Outbreak,Jun 2026,Central African Republic: Cholera Outbreak - J...

In [47]:
df.to_csv(r'/home/ab303el/Documents/virtual internship/CodeAlpha Internship/data/raw/climate_data.csv', index=False)
print('data saved successfully')

data saved successfully

In [3]:
import pandas as pd
df =pd.read_csv('/home/ab303el/Documents/virtual internship/CodeAlpha Internship/data/raw/climate_data.csv')
df.head(10)

,Country,Disaster_Type,Date,Original_Title
0,Indonesia,Earthquake,Aug 2026,Indonesia: Earthquake - Aug 2026
1,Colombia,Earthquake,Aug 2026,Colombia: Earthquake - Aug 2026
2,Myanmar,Floods,Jul 2026,Myanmar: Floods - Jul 2026
3,Afghanistan,Flash Floods,Jul 2026,Afghanistan: Flash Floods - Jul 2026
4,India,Flash Floods,Jul 2026,India: Flash Floods - Jul 2026
5,Kyrgyzstan,Flash Floods,Jul 2026,Kyrgyzstan: Flash Floods - Jul 2026
6,Tajikistan,Floods,Jul 2026,Tajikistan: Floods - Jul 2026
7,Bangladesh,Flash Floods,Jul 2026,Bangladesh: Flash Floods - Jul 2026
8,Georgia,Floods,Jun 2026,Georgia: Floods - Jun 2026
9,Central African Republic,Cholera Outbreak,Jun 2026,Central African Republic: Cholera Outbreak - J...

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11799 entries, 0 to 11798
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         11799 non-null  str
 1   Disaster_Type   11799 non-null  str
 2   Date            11799 non-null  str
 3   Original_Title  11799 non-null  str
dtypes: str(4)
memory usage: 368.8 KB